/*
 * Seat Booking API
 *
 * zupaTech Seat Booking System
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alexhorlock93@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AlexHorlock.BookingSystem.Attributes;
using AlexHorlock.BookingSystem.Models;
using AlexHorlock.BookingSystem.Data;
using AlexHorlock.BookingSystem.Repositories;

namespace AlexHorlock.BookingSystem.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class ZupaAdminApiController : Controller
    { 
        private readonly IBookingSystemService _bookingSystem;

        public ZupaAdminApiController(IBookingSystemService bookingSystem)
        {
            _bookingSystem = bookingSystem;
        }

        /// <summary>
        /// creates a meeting
        /// </summary>
        /// <remarks>Create a Meeting</remarks>
        /// <param name="meeting">Meeting to add</param>
        /// <response code="201">meeting created</response>
        /// <response code="400">invalid input, request invalid</response>
        /// <response code="409">a meeting already exists with that id</response>
        [HttpPost]
        [Route("/Alex-Horlock/SeatBooking/1.0.0/meetings")]
        [ValidateModelState]
        [SwaggerOperation("CreateMeeting")]
        public virtual IActionResult CreateMeeting([FromBody]Meeting meeting)
        { 
            _bookingSystem.AddMeeting(meeting, out int httpStatusCode);
            
            return StatusCode(httpStatusCode);
        }
    }
}
